### ISSUE TITLE
Add .h5p-file validation to H5P-Extractor

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/H5P-Extractor#2]
The H5P-Extractor should validate the .h5p while extracting.

**Comment by sr258** [comment]
I would be willing to work on the validation. It's the next step to installing libraries and uploading packages. I've thought about using [JSON Schema](https://json-schema.org) and a validator library like [ajv](https://github.com/epoberezkin/ajv) to validate the JSON files instead of writing the code myself. Do you have concerns about introducing a dependency for the validator?

**Comment by JPSchellenberg** [comment]
Sure. I will assign you this issue. No, I have no concerns. Whatever gets the project working as soon as possible. :)

**Comment by rtens** [comment]
Since validation has been added to the Editor, I consider this issue closed. Please re-open if not.
